export { DashboardSkeleton } from './DashboardSkeleton';
export { NotesSkeleton } from './NotesSkeleton';
export { AIGenerationSkeleton } from './AIGenerationSkeleton';
export { CollaborationSkeleton } from './CollaborationSkeleton';
export { StudyScheduleSkeleton } from './StudyScheduleSkeleton';
export { IndexSkeleton } from './IndexSkeleton';
export { LoginSkeleton } from './LoginSkeleton';
export { SignInSkeleton } from './SignInSkeleton';
export { SignUpSkeleton } from './SignUpSkeleton';