/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudyScheduleRouteImport } from './routes/study-schedule'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CollaborationRouteImport } from './routes/collaboration'
import { Route as AiGenerationRouteImport } from './routes/ai-generation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpSsoCallbackRouteImport } from './routes/sign-up/sso-callback'
import { Route as SignInSsoCallbackRouteImport } from './routes/sign-in/sso-callback'

const StudyScheduleRoute = StudyScheduleRouteImport.update({
  id: '/study-schedule',
  path: '/study-schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborationRoute = CollaborationRouteImport.update({
  id: '/collaboration',
  path: '/collaboration',
  getParentRoute: () => rootRouteImport,
} as any)
const AiGenerationRoute = AiGenerationRouteImport.update({
  id: '/ai-generation',
  path: '/ai-generation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSsoCallbackRoute = SignUpSsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => SignUpRoute,
} as any)
const SignInSsoCallbackRoute = SignInSsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => SignInRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-generation': typeof AiGenerationRoute
  '/collaboration': typeof CollaborationRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/study-schedule': typeof StudyScheduleRoute
  '/sign-in/sso-callback': typeof SignInSsoCallbackRoute
  '/sign-up/sso-callback': typeof SignUpSsoCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-generation': typeof AiGenerationRoute
  '/collaboration': typeof CollaborationRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/study-schedule': typeof StudyScheduleRoute
  '/sign-in/sso-callback': typeof SignInSsoCallbackRoute
  '/sign-up/sso-callback': typeof SignUpSsoCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-generation': typeof AiGenerationRoute
  '/collaboration': typeof CollaborationRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/study-schedule': typeof StudyScheduleRoute
  '/sign-in/sso-callback': typeof SignInSsoCallbackRoute
  '/sign-up/sso-callback': typeof SignUpSsoCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-generation'
    | '/collaboration'
    | '/dashboard'
    | '/login'
    | '/notes'
    | '/sign-in'
    | '/sign-up'
    | '/study-schedule'
    | '/sign-in/sso-callback'
    | '/sign-up/sso-callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-generation'
    | '/collaboration'
    | '/dashboard'
    | '/login'
    | '/notes'
    | '/sign-in'
    | '/sign-up'
    | '/study-schedule'
    | '/sign-in/sso-callback'
    | '/sign-up/sso-callback'
  id:
    | '__root__'
    | '/'
    | '/ai-generation'
    | '/collaboration'
    | '/dashboard'
    | '/login'
    | '/notes'
    | '/sign-in'
    | '/sign-up'
    | '/study-schedule'
    | '/sign-in/sso-callback'
    | '/sign-up/sso-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiGenerationRoute: typeof AiGenerationRoute
  CollaborationRoute: typeof CollaborationRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  NotesRoute: typeof NotesRoute
  SignInRoute: typeof SignInRouteWithChildren
  SignUpRoute: typeof SignUpRouteWithChildren
  StudyScheduleRoute: typeof StudyScheduleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/study-schedule': {
      id: '/study-schedule'
      path: '/study-schedule'
      fullPath: '/study-schedule'
      preLoaderRoute: typeof StudyScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaboration': {
      id: '/collaboration'
      path: '/collaboration'
      fullPath: '/collaboration'
      preLoaderRoute: typeof CollaborationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-generation': {
      id: '/ai-generation'
      path: '/ai-generation'
      fullPath: '/ai-generation'
      preLoaderRoute: typeof AiGenerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/sso-callback': {
      id: '/sign-up/sso-callback'
      path: '/sso-callback'
      fullPath: '/sign-up/sso-callback'
      preLoaderRoute: typeof SignUpSsoCallbackRouteImport
      parentRoute: typeof SignUpRoute
    }
    '/sign-in/sso-callback': {
      id: '/sign-in/sso-callback'
      path: '/sso-callback'
      fullPath: '/sign-in/sso-callback'
      preLoaderRoute: typeof SignInSsoCallbackRouteImport
      parentRoute: typeof SignInRoute
    }
  }
}

interface SignInRouteChildren {
  SignInSsoCallbackRoute: typeof SignInSsoCallbackRoute
}

const SignInRouteChildren: SignInRouteChildren = {
  SignInSsoCallbackRoute: SignInSsoCallbackRoute,
}

const SignInRouteWithChildren =
  SignInRoute._addFileChildren(SignInRouteChildren)

interface SignUpRouteChildren {
  SignUpSsoCallbackRoute: typeof SignUpSsoCallbackRoute
}

const SignUpRouteChildren: SignUpRouteChildren = {
  SignUpSsoCallbackRoute: SignUpSsoCallbackRoute,
}

const SignUpRouteWithChildren =
  SignUpRoute._addFileChildren(SignUpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiGenerationRoute: AiGenerationRoute,
  CollaborationRoute: CollaborationRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  NotesRoute: NotesRoute,
  SignInRoute: SignInRouteWithChildren,
  SignUpRoute: SignUpRouteWithChildren,
  StudyScheduleRoute: StudyScheduleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
